//GET http://localhost:3000 HTTP/1.1
###

GET https://localhost:3000 HTTP/1.1;
###

GET https://localhost:3000/test HTTP/1.1;
###

GET https://localhost:3000/api/ HTTP/1.1;
###

GET https://localhost:3000/api/orders HTTP/1.1;
###

GET https://localhost:3000/api/ HTTP/1.1;
###


GET https://localhost:3000/api/fruits HTTP/1.1;
###

POST https://localhost:3000/api/fruits HTTP/1.1
Content-Type: application/json

{
    "id": "4",
    "name": "Pear"
}
###


GET https://localhost:3000/api/fruits HTTP/1.1
###


DELETE https://localhost:3000/api/fruits/64f5e4da1fbf9a1695612343 HTTP/1.1
###


POST https://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "hash_user_test_again1",
    "password": "hash_password_test_again1",
    "firstName": "test_firstName1"
}
###


POST https://localhost:3000/api/users/login HTTP/1.1
content-type: application/json
{
 "username": "test2",
 "password": "youwillneverguess"
}
###

POST https://localhost:3000/api/fruits HTTP/1.1
content-type: application/json
Authorization: Bearer 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwidXNlcmlkIjoiNjEy
ZTA2NTQzZDExY2NmZTUwY2ZlNTg4IiwiaWF0IjoxNjMwNTg3MDA3LCJleHAiOjE2MzA1O
TA2MDd9.o-5lq9_IKQgxL1MiwtYrbERkHE5tORq6EkxF3wM_lXQ
{
 "id": "33",
 "name": "Peach"
}
###